### ISSUE TITLE
JUnitParamsRunner incorrectly fails test if a parameter class does not override equals()

### ISSUE THREAD

**Issue by Labalius** [Pragmatists/JUnitParams#108]
Consider the simple test class below. The plain JUnit test passes but the JUnitParams version fails. The new Object() can be replaced by any class that does not override the Object.equals() method. I expect this does not happen often, as most classes do override it.

```java
@RunWith(JUnitParamsRunner.class)
public class BugReportTest
{
    Object value = new Object();
    
    @Test
    @Parameters
    public void valueEqualsItself(Object sameValue)
    {
        assertEquals(value, sameValue);
    }
    
    private Object[][] parametersForValueEqualsItself()
    {
        return new Object[][]{{value}};
    }
    
    @Test
    public void valueEqualsItself()
    {
        assertEquals(value, value);
    }
}
```

**Comment by ukcrpb6** [comment]
This is a side-effect of how parameters are computed

Parameter computation occurs before the test invocation by instantiating an instance of the supplier class (either the current test class or the class specified by the `source` parameter). The parameter set is then computed; for each test a *new* test class instance is created and the test method is invoked with the parameters.

Therefore the source of the parameters `parameterSource` does not obey `parameterSource == this` for the invocation during the test therefore `parameterSource.value != this.value).

It is for this reason that the provided test fails because `sameValue` is not `value` according to `Object#equals`.
