### ISSUE TITLE
Parameterized test fails due to wrong number of params

### ISSUE THREAD

**Issue by dodalovic** [Pragmatists/JUnitParams#110]
When running:

```java
    @Test
    @Parameters({
            "Charles|Barkley|Hi {{firstName}} {{lastName}}!|Hi Charles Barkley!",
            "Charles|Barkley|Hi, {{firstName}} {{lastName}}!|Hi, Charles Barkley!",
    })
    public void sample(String firstName, String lastName, String pattern, String result) {
        System.out.println("firstName = [" + firstName + "], lastName = [" + lastName + "], pattern = [" + pattern +
                "], result = [" + result + "]");
    }
```

The first param set passes, for the second one I get exception:

```
java.lang.IllegalArgumentException: Cannot parse parameters. Did you use ',' or '|' as column separator? Charles|Barkley|Hi, {{firstName}} {{lastName}}!|Hi, Charles Barkley!
```

There seems to be an issue when **commas** and **pipes** in same data set. Not sure if we need some **configuration support** to tell what's the parameters delimiter used.

**Comment by woprzech** [comment]
Hello, we do not plan to implement this functionality. Once we introduce a new configuration option we would have to support it in every other type of parameters providers (from method, external class, file, etc.) It might lead to lots of confusions. 
You can produce your parameters with a `@Parameters.method` instead of `@Parameters.value`. Although we do realize that it will inflict readability of your test.

**Comment by bbobcik** [comment]
I have run into this issue many times - some locales, such as Czech, use comma as a decimal separator. Fortunately escaping works, but the resulting test specification full of backslash noise hurts eyes. I am sad to hear that the maintainer prefers to avoid hypothetical risk ("lot of confusion") instead of improving actual usability of the framework.

In my opinion, adding a single parameter to `@Parameters` annotation and adapting the specification parser would be next to trivial:
```java
@Parameters(separator = '|', value = {
    "testcase 1 | 12,45 | 0,00"
})
public void shouldCheckSomeLogic(String id, String input, String expectedResult) { ... } 
```

**Comment by slawekradzyminski** [comment]
This code is rather ugly workaround, but it works ;)

`private static Object[][] urls() {
        return new Object[][]{
                {"Charles|Barkley|Hi {{firstName}} {{lastName}}!|Hi Charles Barkley!"},
                {"Charles|Barkley|Hi, {{firstName}} {{lastName}}!|Hi, Charles Barkley!"}
        };
    }`

**Comment by laymain** [comment]
It would be nice to have @bbobcik 's proposal implemented
