### ISSUE TITLE
Parameters(method="") - It shows unused methods in IntelliJi

### ISSUE THREAD

**Issue by jotish** [Pragmatists/JUnitParams#133]
<img width="481" alt="screen shot 2017-09-03 at 3 52 26 pm" src="https://user-images.githubusercontent.com/3390136/30002160-0bd0fabc-90c0-11e7-8f79-72e86835b8f8.png">

Any plans to improve this on Idea ?

**Comment by zbychupragmatists** [comment]
We can not do too much about it because in fact these methods are not directly used. Maybe it's possible to write a plugin and help Intellij recognize usage of these methods but we are not gonna do it. If it is annoying for you (for example when using F2 to jump to first problem/warning) you can annotate given methods with

```code:java
@SuppressWarnings("unused")
```
