### ISSUE TITLE
java.lang.IllegalArgumentException when running Samples_of_Usage_Test

### ISSUE THREAD

**Issue by michal-lipski** [Pragmatists/JUnitParams#27]
Since 4874ae9
java.lang.IllegalArgumentException: Number of parameters inside @Parameters annotation doesn't match the number of test method parameters.

junitparams.usage.Samples_of_Usage_Test#wrap_params_with_constructor
junitparams.usage.Samples_of_Usage_Test#load_params_from_any_file

**Comment by Menliat** [comment]
Hello! It happens when the test case parameter is created via his constructor call. In the given example:

    @Test
    @FileParameters(value = "src/test/resources/test.csv", mapper = PersonMapper.class)
    public void load_params_from_any_file(PersonTest.Person person) { }

Actual parameters (of the TestMethod in JUnitParams core) are [String, Integer] pairs. Firstly, the runner tries to use some converters for the given parameters. When the conversion throws an exception, this exception get logged, and then the runner attempts to wrap the parameters into a class of the first method argument (via reflection call to a constructor with the same signature). So, it doesn't break the test execution, and it looks like just a logging issue, that can be fixed by removing e.printStackTrace() line in castParamsFromObjects(Object params) method of InvokeParameterisedMethod class. Do you expect any general solution avoiding the exception catching?

**Comment by michal-lipski** [comment]
You are right this is a logging issue. 
Except of fact that this exception handling is not very elegant solution, everything works fine. 
Fix for now was to remove exception logging.
