### ISSUE TITLE
Question: computed list of parameters

### ISSUE THREAD

**Issue by martinda** [Pragmatists/JUnitParams#39]
Do I have to know the actual parameter values ahead of time or can they be generated on the fly automatically? For example this parameter could be a seed to a RNG and I would pre-generate the seeds to run the test N different times with each test getting a different seed value. Only I would use a function to generate the seeds so I would not have to type them or save them to a file. Thanks.

**Comment by michal-lipski** [comment]
You can define method that will provide parameters for your test:

```java
    @Test
    @Parameters
    public void params_in_default_method(String p1, Integer p2) { }
    private Object parametersForParams_in_default_method() {
        return new Object[]{new Object[]{"AAA", 1}, new Object[]{"BBB", 2}};
    }

    @Test
    @Parameters(method = "named1")
    public void params_in_named_method(String p1, Integer p2) { }
    private Object named1() {
        return new Object[]{"AAA", 1};
    }
```

Check: https://github.com/Pragmatists/JUnitParams/blob/master/src/test/java/junitparams/usage/Samples_of_Usage_Test.java

**Comment by ChrisArrington** [comment]
I have a question/concern along these lines. In my case I'm using some immutable objects with values pre-set to be returned for certain getter methods. I typically create an instance of the objects in the constructor of my test, storing it as an instance variable in the test class. On each instance I initialize each getter methods to return a random value, which I also keep as instance variables. In each of my test methods the I can compare the results from the test with the appropriate instance variable value. This technique currently doesn't work in JUnitParams because the instance of the test class used to initialize the cached parameters is different from the one used to run the actual test.

I know that one solution to this would be to not use randomized values, but I'd rather not use hard coded values. This basically comes down to being able to use instance variables in your parameter methods. 

Looking through the code I thought one way it could be done would be to somehow optionally set the cached parameters just before the test is run, or always set the parameters at this time. Maybe this could be done with a certain annotation or annotation parameter.

**Comment by grzesuav** [comment]
@ChrisArrington wouldn't be possible to extract those instance fields as additional parameters ? 

Could you post an example code to be sure that we are on the same page ?

**Comment by zbychupragmatists** [comment]
Closing because @ChrisArrington is not answering. If you have any more doubts - please open new issue.
